(load (compile-file "acl_monadic_functions.lisp"))
(load (compile-file "acl_dyadic_functions.lisp"))
(load (compile-file "acl_monadic_operators.lisp"))
(load (compile-file "acl_dyadic_operators.lisp"))
(load (compile-file "exercises.lisp"))
